apiVersion: v1
kind: Service
metadata:
  name: webservice
spec:
  selector:
    app: webapp
  ports:
    - name: http
      port: 80
      nodePort: 30080
  
  type: NodePort

---

apiVersion: v1
kind: Service
metadata:
  name: queueservice
spec:
  selector:
    app: queue
    release: "1"
  ports:
    - name: http
      port: 8161
      nodePort: 30010
  
  type: NodePort